development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bjtauvwsibfyio:127784cbd7d7d7db77da3fabe6778ccdcbbf29ad0bfb676be6260a8be6929f16@ec2-54-83-59-120.compute-1.amazonaws.com:5432/ddbl8t6nqn1q6k
  channel_prefix: test_app_production
